## language: pt
#Funcionalidade: Solicitar cálculo de taxas (Sucesso)
#@CT4.1.1.1
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Usina em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Março 2014" para o campo "Mês inicial"
#E eu informo o valor "Agosto 2014" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "UHE JIRAU" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "UHE JIRAU" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: UHE JIRAU; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 03/2014; Mês final de cálculo: 08/2014; Status: Agendado"
#@CT4.1.1.2
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Março 2010" para o campo "Mês inicial"
#E eu informo o valor "Abril 2010" para o campo "Mês final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI ACARAY" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI ACARAY" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 03/2010; Mês final de cálculo: 04/2010; Status: Agendado"
#@CT4.1.2.1
#Cenário: Solicitar cálculo de Taxas para período após a 01/10/2014 para Instalação do tipo Usina em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Outubro 2014" para o campo "Mês inicial"
#E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 10/2014; Mês final de cálculo: 02/2015; Status: Agendado"
#@CT4.1.2.2
#Cenário: Solicitar cálculo de Taxas para período após a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Outubro 2014" para o campo "Mês inicial"
#E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
##Eeu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 10/2014; Mês final de cálculo: 02/2015; Status: Agendado"
#@CT4.1.3.1
#Cenário: Solicitar cálculo de Taxas para período que compreenda data anterior a 1/10/2014 e posterior a 01/10/2014 para Instalação do tipo Usina em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Setembro 2014" para o campo "Mês inicial"
#E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver 1 item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 09/2014; Mês final de cálculo: 02/2015; Status: Agendado"
#@CT4.1.3.2
#Cenário: Solicitar cálculo de Taxas para período que compreenda data anterior a 1/10/2014 e posterior a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
##quando eu informo o valor "Setembro 2014" para o campo "Mês inicial"
#E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
#E eu informo o valor "01/01/2020" para o campo "Data Inicial"
#E eu informo o valor "02/01/2020" para o campo "Data Final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 09/2014; Mês final de cálculo: 02/2015; Status: Agendado"
##Funcionalidade: Solicitar cálculo de taxas (Insucesso)
#@CT4.2.1
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Usina em que ao menos uma esteja em operação comercial e outra esteja suspensa
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Janeiro 2014" para o campo "Mês inicial"
#E eu informo o valor "Agosto 2014" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu informo "Cálculo de taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu escolho o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: U.SOBRADINHO; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2014; Mês final de cálculo: 08/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CAMPOS; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2014; Mês final de cálculo: 08/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2014; Mês final de cálculo: 08/2014; Status: Agendado"
#@CT4.2.2
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Usina em que ao menos uma esteja em operação comercial e outra esteja desativada
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Fevereiro 2014" para o campo "Mês inicial"
#E eu informo o valor "Setembro 2014" para o campo "Mês final"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "TERMONORTE I" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "TERMONORTE I" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: U.SOBRADINHO; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 02/2014; Mês final de cálculo: 09/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: TERMONORTE I; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 02/2014; Mês final de cálculo: 09/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 02/2014; Mês final de cálculo: 09/2014; Status: Agendado"
#@CT4.2.3
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Usina em que ao menos uma esteja em operação comercial e outra que não tenha entrado ainda em operação
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Julho 2014" para o campo "Mês inicial"
#E eu informo o valor "Julho 2014" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu aperto o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: U.SOBRADINHO; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 07/2014; Mês final de cálculo: 07/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CAMPOS; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 07/2014; Mês final de cálculo: 07/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 07/2014; Mês final de cálculo: 07/2014; Status: Agendado"
#@CT4.2.4
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Interligação Internacional em que ao menos uma esteja em operação comercial e outra esteja suspensa
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Janeiro 2014" para o campo "Mês inicial"
#E eu informo o valor "Julho 2014" para o campo "Mês final"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "CI CV.GARABI 1" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu escolho o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "CI CV.GARABI 1" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2014; Mês final de cálculo: 07/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.GARABI 1; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2014; Mês final de cálculo: 07/2014; Status: Agendado"
#@CT4.2.5
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Interligação Internacional em que ao menos uma esteja em operação comercial e outra esteja desativada
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Julho 2014" para o campo "Mês inicial"
#E eu informo o valor "Setembro 2014" para o campo "Mês final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "GARABI" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu escolho o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "CI CV.GARABI 1" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 07/2014; Mês final de cálculo: 09/2014; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.GARABI 1; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 07/2014; Mês final de cálculo: 09/2014; Status: Agendado"
#@CT4.2.6
#Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Interligação Internacional em que ao menos uma esteja em operação comercial e outra que não tenha entrado ainda em operação
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#Quando eu informo o valor "Janeiro 2002" para o campo "Mês inicial"
#E eu informo o valor "Março 2002" para o campo "Mês final"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "CI CV.GARABI 2" na lista "Interligações Internacionais"
#E eu aperto o botão "Agendar cálculo"
#E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu escolho o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Interligações Internacionais"
#E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
#E eu seleciono o item "CI CV.GARABI 2" na lista "Interligações Internacionais"
#E eu aperto o botão "Pesquisar"
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2002; Mês final de cálculo: 03/2002; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.GARABI 2; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 01/2002; Mês final de cálculo: 03/2002; Status: Agendado"
#@CT4.2.7
#Cenário: Solicitar cálculo de Taxas para período após a 01/10/2014 para Instalação do tipo Usina em que ao menos uma esteja em operação comercial e outra esteja suspensa
#Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
#E eu esteja na página "Solicitar cálculo de taxa"
#E a instalação "CAMPOS" esteja suspensa em "01/10/2014"
#Quando eu informo o valor "Novembro 2014" para o campo "Mês inicial"
#E eu informo o valor "Março 2015" para o campo "Mês final"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu aperto o botão "Agendar cálculo"
##eu informo o valor "01/01/2020" para o campo "Data de agendamento"
#E eu informo o valor "10:00" para o campo "Hora de agendamento"
#E eu aperto o botão "Agendar"
#E eu escolho o item de menu "Consultar agendamentos"
#E eu informo o valor "Cálculo das taxas" para o campo "Origem do agendamento"
#E eu aperto a guia "Usinas"
#E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#E eu seleciono o item "CAMPOS" na lista "Usinas"
#E eu aperto o botão "Pesquisar
#Então eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: U.SOBRADINHO; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 11/2014; Mês final de cálculo: 03/2015; Status: Agendado"
#E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CAMPOS; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 11/2014; Mês final de cálculo: 03/2015; Status: Agendado"
