# language: pt
Funcionalidade: Consultar taxas informando período para filtragem
@CT2.1.1
Cenário: Mês Inicial válido e Mês Final válido (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIFa mensal: 0,207263"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIFa mensal: 0,192284"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 03/2008; TEIP mensal: 0,129514; TEIFa mensal: 0,312551"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,009309; TEIFa mensal: 0,488413"
@CT2.1.2
Cenário: Mês Inicial menor ou igual a Mês Final (Sucesso) 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 item no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,009309; TEIFa mensal: 0,488413"
@CT2.1.3
Cenário: Mês Inicial maior ou igual a 01/01/2001 e menor que a Data Corrente e Mês Final menor que a Data Corrente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "03/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 03/2008; TEIP mensal: 0,129514; TEIFa mensal: 0,312551"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,009309; TEIFa mensal: 0,488413"
#Funcionalidade: Consultar taxas informando período para filtragem
@CT2.2.1
Cenário: Mês Inicial válido e Mês Final inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "03/2008" para o campo "Mês inicial"
E eu informo o valor "14/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código  "RS_MENS_005" e crítica "Mês final"
@CT2.2.2
Cenário: Mês Inicial inválido e Mês Final válido (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "13/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_010" e crítica "Mês inicial"
@CT2.2.3
Cenário: Mês Inicial sem preenchimento e Mês Final inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "14/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Mês inicial"
E eu deveria ver a mensagem de erro de código "RS_MENS_005" e crítica "Mês final"
@CT2.2.4
Cenário: Mês Inicial inválido e Mês Final sem preenchimento (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "13/2008" para o campo "Mês inicial"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_010" e crítica "Mês inicial"
E eu deveria ver a deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Mês final"
@CT2.2.5
Cenário: Mês Inicial maior que Mês Final (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_004"
@CT2.2.6
Cenário: Mês Inicial maior ou igual a Mês Corrente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2020" para o campo "Mês inicial"
E eu informo o valor "01/2020" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
E eu deveria ver a mensagem de erro de código "RS_MENS_026" e crítica "Mês inicial; Mês final"
@CT2.2.7
Cenário: Mês Final maior ou igual a Mês Corrente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2020" para o campo "Mês inicial"
E eu informo o valor "04/2020" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_026" e crítica "Mês final; Mês final"
#
@CT2.2.8
Cenário: Mês Inicial menor que 01/2001 (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2000" para o campo "Mês inicial"
E eu informo o valor "04/2001" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_023" e crítica "Mês inicial"
@CT2.2.9
Cenário: Mês Final menor que 01/2001 (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2000" para o campo "Mês inicial"
E eu informo o valor "04/2000" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_023" e crítica "Mês inicial"; "Mês final"
@CT2.2.10
Cenário: Mês Inicial sem preenchimento (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Mês inicial"
@CT2.2.11
Cenário: Mês Final sem prenchimento (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2008" para o campo "Mês inicial"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Mês final"
#Funcionalidade: Consultar taxas informando filtro por tipo de taxa
@CT2.3.1
Cenário: Selecionar TEIP mensal (Sucesso); 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,032232"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIP mensal: 0,058113"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,003758"
#
@CT2.3.2
Cenário: Selecionar TEIP acum (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,0173869599"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP acumulada: 0,0178939104"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIP acumulada: 0,0188209508"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIP acumulada: 0,01879967"
@CT2.3.3
Cenário: Selecionar TEIFa mensal (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIFa mensal: 0,000736"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIFa mensal: 0,002984"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIFa mensal: 0,172301"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIFa mensal: 0,402023"
@CT2.3.4
Cenário: Selecionar TEIFa acum (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIFa acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIFa acumulada: 0,00127479096"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIFa acumulada: 0,00132453104"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIFa acumulada: 0,00419620797"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIFa acumulada: 0,0108965999"
@CT2.3.5
Cenário: 5) Selecionar TEIP_fc mensal (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "03/2010" para o campo "Mês inicial"
E eu informo o valor "03/2010" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP_fc mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "PETROLINA" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 itens no grid "PETROLINA"
E eu deveria ver um item no grid "PETROLINA" com valor: "Mês Referência: 03/2010; TEIP_fc mensal: 0,344466895"
@CT2.3.6
Cenário: Selecionar TEIP_fc (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "03/2010" para o campo "Mês inicial"
E eu informo o valor "03/2010" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP_fc"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "PETROLINA" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 itens no grid "PETROLINA"
E eu deveria ver um item no grid "PETROLINA" com valor: "Mês Referência: 03/2010; TEIP_fc acumulada: 0,0461663306"
@CT2.3.7
Cenário: Selecionar TEIF_fc mensal (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2013" para o campo "Mês inicial"
E eu informo o valor "01/2013" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIFa_fc mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "UTE P.FERRO 1" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 itens no grid "UTE P.FERRO 1"
E eu deveria ver um item no grid "UTE P.FERRO 1" com valor: "Mês Referência: 01/2013; TEIFa_fc mensal: 0,164707705"
@CT2.3.8
Cenário: Selecionar TEIF_fc (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2013" para o campo "Mês inicial"
E eu informo o valor "01/2013" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIFa_fc"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "UTE P.FERRO 1" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 itens no grid "UTE P.FERRO 1"
E eu deveria ver um item no grid "UTE P.FERRO 1" com valor: "Mês Referência: 01/2013; TEIFa_fc acumulada: 0,00552687002"
@CT2.3.9
Cenário: Selecionar TEIP_oper mensal (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP_oper mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP oper mensal: 0,0171099603"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP oper mensal: 0,0322318003"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIP oper mensal: 0,0581130497"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIP oper mensal: 0,00375771592"
@CT2.3.10
Cenário: Selecionar TEIP_oper acum (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP_oper acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP oper acumulada: 0,0173869599"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP oper acumulada: 0,0178939104"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIP oper acumulada: 0,0188209508"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIP oper acumulada: 0,01879967"
#
@CT2.3.11
Cenário: Selecionar TEIF_oper mensal (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIF_oper mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIF oper mensal: 0,00189744204"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIF oper mensal: 0,148415595"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIF oper mensal: 0,191511095"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIF oper mensal: 0,402023494"
#
@CT2.3.12
Cenário: Selecionar TEIF_oper acum (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIF_oper acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIF oper acumulada: 0,00158049294"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIF oper acumulada: 0,00405408582"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIF oper acumulada: 0,00724593783"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIF oper acumulada: 0,0139463302"
@CT2.3.13
Cenário: Índice de Indisponibilidade (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "12/2013" para o campo "Mês inicial"
E eu informo o valor "12/2013" para o campo "Mês final"
E eu seleciono o tipo de taxa "Índice de Indisponibilidade"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 item no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 12/2013; Indisponibilidade: 0,11266"
@CT2.3.14
Cenário: Escolher mais de um tipo de Taxa (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu seleciono o tipo de taxa "TEIP oper acumulada"
E eu seleciono o tipo de taxa "TEIF oper acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 item no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; "TEIF mensal: 0,00189744204; TEIFa mensal: 0,000736; TEIP oper acumulada: 0,0173869599; "TEIF oper acumulada: 0,00158049294"
#Funcionalidade: Consultar taxas informando filtro por tipo de instalação
@CT2.4.1
Cenário: Sem escolher instalação (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "12/2013" para o campo "Mês inicial"
E eu informo o valor "12/2013" para o campo "Mês final"
E eu seleciono o tipo de taxa "Índice de Indisponibilidade"
E eu aperto a lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Instalação"
@CT2.4.2
Cenário: Escolhendo algumas usinas e interligações internacionais (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a guia "Usinas"
E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
#
Então eu deveria ver 1 itens selecionados no grid "Usinas" com valor "Nome: U.SOBRADINHO"
E eu deveria ver a guia "Interligação Internacionais" indisponível
@CT2.4.3
Cenário: Escolhendo algumas usinas (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; TEIF mensal: 0,00189744204"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,032232; TEIF mensal: 0,148415595"
E eu deveria ver 2 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS"" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIF mensal: 0,198454306"
@CT2.4.4
Cenário: Escolhendo algumas interligações internacionais  (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acuml"
E eu seleciono o tipo de taxa "TEIF acumulada"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CI CV.GARABI 1" na lista "Interligações Internacionais"
E eu seleciono o elemento "CI CV.GARABI 2" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,292148; TEIF mensal: 0,158050597"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 02/2008; TEIP acumulada: 0,292148; TEIF mensal: 0,157815397"
E eu deveria ver 2 itens no grid "CI CV.GARABI 2"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,257341; TEIF mensal: 0,158710495"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 02/2008; TEIP acumulada: 0,257341; TEIF mensal: 0,158475399"
@CT2.4.5
Cenário: Escolhendo todas as usinas  (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono todos os elementos na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 8 itens um em cada grid
E eu deveria ver no grid "BENTO MUNHOZ"
E eu deveria ver um item no grid "BENTO MUNHOZ" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,003657; TEIF mensal: 0,25"
E eu deveria ver no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver no grid "P.MEDICI"
E eu deveria ver um item no grid "P.MEDICI" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,226553; TEIF mensal: 0,544354379"
E eu deveria ver no grid "U.CHARQUEADAS"
E eu deveria ver um item no grid "U.CHARQUEADAS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,017396; TEIF mensal: 0,041581601"
E eu deveria ver no grid "U.SOBRADINHO"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,05317; TEIF mensal: 0"
E eu deveria ver no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; TEIF mensal: 0,001897442"
E eu deveria ver no grid "UT MARIO LAGO"
E eu deveria ver um item no grid "UT MARIO LAGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,184152; TEIF mensal: 0,304034412"
# E eu deveria ver no grid "UT. FORTALEZA"
E eu deveria ver um item no grid "UT. FORTALEZA" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,161463; TEIF mensal: 0"
@CT2.4.6
Cenário: Escolhendo todas as interligações internacionais  (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2007" para o campo "Mês inicial"
E eu informo o valor "04/2007" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Interligações internacionais"
E eu seleciono todos os elementos na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens um em cada grid
E eu deveria ver no grid "CI ACARAY"
E eu deveria ver um item no grid "CI ACARAY" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,127338; TEIF mensal: 0,105732203"
E eu deveria ver no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.GARABI 2"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.URUGUAIANA"
E eu deveria ver um item no grid "CI CV.URUGUAIANA" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,010509; TEIF mensal: 0,383248687"
#Funcionalidade: Consultar taxas informando filtro pelo nome da instalação
@CT2.5.1
Cenário: Usar um nome de instalação usina existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "USINA XINGO" no campo "Nome" na lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
Então eu deveria ver 4 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,0173869599"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,0178939104"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 03/2008; TEIP mensal: 0,0188209508"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,01879967"
#
@CT2.5.2
Cenário: Usar um nome de instalação usina inexistente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "OGNIX ANISU" no campo "Nome" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
Então eu não deveria ver nenhuma taxa de "Usinas"
@CT2.5.3
Cenário: Usar um nome de instalação Interligação internacional existente  (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acumulada"
E eu seleciono o tipo de taxa "TEIF acumulada"
E eu aperto a lista "Interligações internacionais"
E eu informo o valor  "CI CV.GARABI 1" no campo "Nome" na lista "Interligações internacionais"
E eu seleciono o elemento  "CI CV.GARABI 1" na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 1 item no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,292148; TEIF acumulada: 0,158050597"
@CT2.5.4
Cenário: Usar um nome de instalação  Interligação internacional  inexistente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Interligações internacionais"
E eu informo o valor "CASA" no campo "Nome" na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu não deveria ver nenhuma taxa de "Interligações Internacionais"
@CT2.5.5
Cenário: Escolher mais de um nome de instalação existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acumulada"
E eu seleciono o tipo de taxa "TEIF acumulada"
E eu aperto a lista "Interligações internacionais"
E eu informo o valor "CI" no campo "Nome" na lista "Interligações internacionais"
E eu seleciono todos os elementos na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens um em cada grid
E eu deveria ver no grid "CI ACARAY"
E eu deveria ver um item no grid "CI ACARAY" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0; TEIF acumulada: 0"
E eu deveria ver no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,292148; TEIF acumulada: 0,158050597"
E eu deveria ver no grid "CI CV.GARABI 2"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,257341; TEIF acumulada: 0,158710495"
E eu deveria ver no grid "CI CV.URUGUAIANA"
E eu deveria ver um item no grid "CI CV.URUGUAIANA" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,014449; TEIF acumulada: 0"
@CT2.5.6
Cenário: Escolher um nome de instalação usina existente e um nome instalação usina inexistente (Insucesso)
#Não reproduzível/necessário
#
@CT2.5.7
Cenário: Escolher um nome de instalação interligação Internacional existente e um nome instalação interligação Internacional inexistente (Insucesso)
#Não reproduzível/necessário
#
#Funcionalidade: Consultar taxas informando filtro por tipo
@CT2.6.1
Cenário: Não escolher o tipo de usina (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono todos os elementos na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 8 itens um em cada grid
E eu deveria ver no grid "BENTO MUNHOZ"
E eu deveria ver um item no grid "BENTO MUNHOZ" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,003657; TEIF mensal: 0,25"
E eu deveria ver no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver no grid "P.MEDICI"
E eu deveria ver um item no grid "P.MEDICI" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,226553; TEIF mensal: 0,544354379"
E eu deveria ver no grid "U.CHARQUEADAS"
E eu deveria ver um item no grid "U.CHARQUEADAS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,017396; TEIF mensal: 0,041581601"
E eu deveria ver no grid "U.SOBRADINHO"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,05317; TEIF mensal: 0"
E eu deveria ver no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; TEIF mensal: 0,001897442"
E eu deveria ver no grid "UT MARIO LAGO"
E eu deveria ver um item no grid "UT MARIO LAGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,184152; TEIF mensal: 0,304034412"
# E eu deveria ver no grid "UT. FORTALEZA"
E eu deveria ver um item no grid "UT. FORTALEZA" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,161463; TEIF mensal: 0"
@CT2.6.2
Cenário: Escolher Hidrelétricas (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "03/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu seleciono o tipo de taxa "TEIP oper mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "UTE" no campo "Tipo" na lista "Usinas"
E eu seleciono o elemento "U.SOBRADINHO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
Então eu deveria ver 3 itens no grid "U.SOBRADINHO"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,05317; TEIF mensal: 0; TEIFa  mensal: 0; TEIP oper  mensal: 0,0531698018"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 02/2008; TEIP  mensal: 0,00793; TEIF  mensal: 0,0348607711; TEIFa  mensal: 0,019037; TEIP oper  mensal: 0,00793023594"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 03/2008; TEIP  mensal: 0; TEIF  mensal: 0,169158697; TEIFa  mensal: 0,004951; TEIP oper  mensal: 0"
@CT2.6.3
Cenário: Escolher Termelétricas (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "UTE" no campo "Tipo" na lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395; TEIFa mensal: 0,207263"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIF mensal: 0,198454306; TEIFa mensal: 0,192284"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 03/2008; TEIP mensal: 0,129514; TEIF mensal: 0,366282314; TEIFa mensal: 0,312551"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 04/2008; TEIP mensal: 0,009309; TEIF mensal: 0,736644626; TEIFa mensal: 0,488413"
#
@CT2.6.4
Cenário: Escolher tipo inexistente de usina (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "OGN" no campo "Tipo" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu não deveria ver nenhuma taxa de "Interligações Internacionais"
@CT2.6.5
Cenário: Escolher mais de um tipo de usina (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "USINA XINGO" na lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; TEIF mensal: 0,00189744204"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,032232; TEIF mensal: 0,148415595"
E eu deveria ver 2 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIF mensal: 0,198454306"
#Funcionalidade: Consultar taxas informando filtro pelo nome do agente
@CT2.7.1
Cenário: Usar um nome de agente de usina existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "FURNAS" no campo "Agente" na lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIF mensal: 0,198454306"
@CT2.7.2
Cenário: Usar um nome de agente de usina inexistente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "SANRUF" no campo "Agente" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
Então eu não deveria ver nenhuma taxa de "Usinas"
@CT2.7.3
Cenário: Usar um nome de agente de Interligação internacional existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acumulada"
E eu seleciono o tipo de taxa "TEIF acumulada"
E eu seleciono o tipo de taxa "TEIFa acumulada"
E eu aperto a lista "Usinas"
E eu informo o valor "CIEN" no campo "Agente" na lista "Interligações Internacionais"
E eu seleciono o elemento "CI CV.GARABI 1" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
#
Então eu deveria ver 1 item no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 01/2008; TEIP acumulada: 0,292148; TEIF acumulada: 0,158050597; TEIFa acumulada: 0,00002"
@CT2.7.4
Cenário: Usar um nome de agente de  Interligação internacional  inexistente (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu informo o valor "SANRUF" no campo "Agente" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
#
Então eu não deveria ver nenhuma taxa de "Interligações Internacionais"
@CT2.7.5
Cenário: Escolher mais de um agente por nome e por instalação (Insucesso)
#Não reproduzível/necessário
#
@CT2.7.6
Cenário: Escolher agente por nome de agente e instalação usina existente e um agente por nome e instalação usina inexistente (Insucesso)
#Não reproduzível/necessário
#
@CT2.7.7
Cenário: Escolher um agente por nome e instalação interligação Internacional existente e um um agente por nome e instalação interligação Internacional inexistente (Insucesso)
#Não reproduzível/necessário
#
#Funcionalidade: Consultar taxas informando instalações
@CT2.8.1
Cenário: Não escolher Usinas ou Interligações Internacionais (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "04/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto o botão "Pesquisar"
#
Então eu deveria ver a mensagem de erro de código "RS_MENS_002" e crítica "Instalação"
@CT2.8.2
Cenário: Escolher apenas uma Usina (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu seleciono o tipo de taxa "TEIP_oper mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu aperto o botão "Pesquisar"
#
Então eu deveria ver 2 itens no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395; TEIFa mensal: 0,207263; TEIP oper mensal: 0,3197245"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 02/2008; TEIP mensal: 0,001789; TEIF mensal: 0,198454306; TEIFa mensal: 0,192284; TEIP oper mensal: 0,00178879302"
@CT2.8.3
Cenário: Escolher apenas uma Interligação Internacional (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Interligações Internacionais"
E eu seleciono o elemento "CI CV.GARABI 1" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 2 itens no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 01/2008; TEIP: 0,292148; TEIF: 0,158050597"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 02/2008; TEIP: 0,292148; TEIF: 0,157815397"
@CT2.8.4
Cenário: Escolher uma Usina e uma Interligação Internacional (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "02/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
#
Então eu deveria ver 1 itens selecionados no grid "Usinas" com valor "Nome: CAMPOS"
E eu deveria ver a guia "Interligações Internacionais" indisponível
@CT2.8.5
Cenário: Escolher várias Usinas e várias Interligações Internacionais (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Usinas"
E eu seleciono o elemento "BENTO MUNHOZ" na lista "Usinas"
E eu seleciono o elemento "CAMPOS" na lista "Usinas"
E eu seleciono o elemento "P.MEDICI" na lista "Usinas"
Então eu deveria ver 3 itens selecionados no grid "Usinas" 
E eu deveria ver no grid "Usinas" com valor "Nome: BENTO MUNHOZ"
E eu deveria ver no grid "Usinas" com valor "Nome: CAMPOS"
E eu deveria ver no grid "Usinas" com valor "Nome: P.MEDICI"
E eu deveria ver a guia "Interligações Internacionais" indisponível
@CT2.8.6
Cenário: Escolher todas as Usinas (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu seleciono o tipo de taxa "TEIFa mensal"
E eu aperto a lista "Usinas"
E eu seleciono todos os elementos na lista "Usinas"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 8 itens um em cada grid
E eu deveria ver no grid "BENTO MUNHOZ"
E eu deveria ver um item no grid "BENTO MUNHOZ" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,003657; TEIF mensal: 0,25"
E eu deveria ver no grid "CAMPOS"
E eu deveria ver um item no grid "CAMPOS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,319725; TEIF mensal: 0,262479395"
E eu deveria ver no grid "P.MEDICI"
E eu deveria ver um item no grid "P.MEDICI" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,226553; TEIF mensal: 0,544354379"
E eu deveria ver no grid "U.CHARQUEADAS"
E eu deveria ver um item no grid "U.CHARQUEADAS" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,017396; TEIF mensal: 0,041581601"
E eu deveria ver no grid "U.SOBRADINHO"
E eu deveria ver um item no grid "U.SOBRADINHO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,05317; TEIF mensal: 0"
E eu deveria ver no grid "USINA XINGO"
E eu deveria ver um item no grid "USINA XINGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,01711; TEIF mensal: 0,001897442"
E eu deveria ver no grid "UT MARIO LAGO"
E eu deveria ver um item no grid "UT MARIO LAGO" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,184152; TEIF mensal: 0,304034412"
# E eu deveria ver no grid "UT. FORTALEZA"
E eu deveria ver um item no grid "UT. FORTALEZA" com valor: "Mês Referência: 01/2008; TEIP mensal: 0,161463; TEIF mensal: 0"
@CT2.8.7
Cenário: Escolher todas as Interligações Internacionais (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "01/2008" para o campo "Mês inicial"
E eu informo o valor "01/2008" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP acumulada"
E eu seleciono o tipo de taxa "TEIF acumulada"
E eu seleciono o tipo de taxa "TEIFa acumulada"
E eu aperto a lista "Interligações internacionais"
E eu seleciono todos os elementos na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens um em cada grid
E eu deveria ver no grid "CI ACARAY"
E eu deveria ver um item no grid "CI ACARAY" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,127338; TEIF mensal: 0,105732203"
E eu deveria ver no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.GARABI 2"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.URUGUAIANA"
E eu deveria ver um item no grid "CI CV.URUGUAIANA" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,010509; TEIF mensal: 0,383248687"
@CT2.8.8
Cenário: Escolher todas as Usinas e todas as Interligações Internacionais (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas"
Quando eu informo o valor "04/2007" para o campo "Mês inicial"
E eu informo o valor "04/2007" para o campo "Mês final"
E eu seleciono o tipo de taxa "TEIP mensal"
E eu seleciono o tipo de taxa "TEIF mensal"
E eu aperto a lista "Interligações internacionais"
E eu seleciono todos os elementos na lista "Interligações internacionais"
E eu aperto o botão "Pesquisar"
Então eu deveria ver 4 itens um em cada grid
E eu deveria ver no grid "CI ACARAY"
E eu deveria ver um item no grid "CI ACARAY" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,127338; TEIF mensal: 0,105732203"
E eu deveria ver no grid "CI CV.GARABI 1"
E eu deveria ver um item no grid "CI CV.GARABI 1" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.GARABI 2"
E eu deveria ver um item no grid "CI CV.GARABI 2" com valor: "Mês Referência: 04/2007; TEIP mensal: 1; TEIF mensal: 0"
E eu deveria ver no grid "CI CV.URUGUAIANA"
E eu deveria ver um item no grid "CI CV.URUGUAIANA" com valor: "Mês Referência: 04/2007; TEIP mensal: 0,010509; TEIF mensal: 0,383248687"
