# language: pt

Funcionalidade: Solicitar cálculo de taxas (Sucesso)

Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Usina em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Março 2014" para o campo "Mês inicial"
	E eu informo o valor "Agosto 2014" para o campo "Mês final"
	E eu aperto a guia "Usinas"
	E eu seleciono o item "UHE JIRAU" na lista "Usinas"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Usinas"
	#	E eu seleciono o item "UHE JIRAU" na lista "Usinas"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: UHE JIRAU; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 03/2014; Mês final de cálculo: 08/2014; Status: Agendado"

Cenário: Solicitar cálculo de Taxas para período anterior a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Março 2010" para o campo "Mês inicial"
	E eu informo o valor "Abril 2010" para o campo "Mês final"
	E eu aperto a guia "Interligações Internacionais"
	E eu seleciono o item "CI ACARAY" na lista "Interligações Internacionais"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Interligações Internacionais"
	#	E eu seleciono o item "CI ACARAY" na lista "Interligações Internacionais"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 03/2010; Mês final de cálculo: 04/2010; Status: Agendado"

Cenário: Solicitar cálculo de Taxas para período após a 01/10/2014 para Instalação do tipo Usina em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Outubro 2014" para o campo "Mês inicial"
	E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
	E eu aperto a guia "Usinas"
	E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Usinas"
	#	E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 10/2014; Mês final de cálculo: 02/2015; Status: Agendado"

Cenário: Solicitar cálculo de Taxas para período após a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Outubro 2014" para o campo "Mês inicial"
	E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
	E eu aperto a guia "Interligações Internacionais"
	E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Interligações Internacionais"
	#	E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 10/2014; Mês final de cálculo: 02/2015; Status: Agendado"


Cenário: Solicitar cálculo de Taxas para período que compreenda data anterior a 1/10/2014 e posterior a 01/10/2014 para Instalação do tipo Usina em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Setembro 2014" para o campo "Mês inicial"
	E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
	E eu aperto a guia "Usinas"
	E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Usinas"
	#	E eu seleciono o item "STO.ANT.JARI" na lista "Usinas"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver 1 item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: STO.ANT.JARI; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 09/2014; Mês final de cálculo: 02/2015; Status: Agendado"

Cenário: Solicitar cálculo de Taxas para período que compreenda data anterior a 1/10/2014 e posterior a 01/10/2014 para Instalação do tipo Interligação Internacional em operação comercial
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Solicitar cálculo de taxa"
	Quando eu informo o valor "Setembro 2014" para o campo "Mês inicial"
	E eu informo o valor "Fevereiro 2015" para o campo "Mês final"
	E eu aperto a guia "Interligações Internacionais"
	E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
	E eu aperto o botão "Agendar cálculo"
	E eu informo o valor "01/01/2020" para o campo "Data de agendamento"
	E eu informo o valor "10:00" para o campo "Hora de agendamento"
	E eu aperto o botão "Agendar"
	#	Então eu deveria ver a mensagem de sucesso de código "RS_MENS_001"
	#	E eu aperto o item de menu "Consultar agendamentos"
	#	E eu seleciono "Cálculo de Taxas" para o campo "Origem de agendamento"
	#	E eu informo o valor "01/01/2020" para o campo "Data Inicial"
	#	E eu informo o valor "02/01/2020" para o campo "Data Final"
	#	E eu aperto a guia "Interligações Internacionais"
	#	E eu seleciono o item "CI CV.URUGUAIANA" na lista "Interligações Internacionais"
	#	E eu aperto o botão "Pesquisar"
	#	E eu deveria ver um item no grid "Agendamentos de Cálculo de Taxas" com valor "Instalação: CI CV.URUGUAIANA; Data Hora: 01/01/2020 10:00; Solicitante: cnos; Mês Inicial de cálculo: 09/2014; Mês final de cálculo: 02/2015; Status: Agendado"
	