# language: pt
Funcionalidade: Consultar Taxa de Referência filtrando pela IP
@CT3.1.1.1
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP existente (Usina) com usuário "cnos" e perfil "CNOS" 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "0,08091" para o campo "IP" na guia "Usinas"
Então eu deveria ver 2 itens na lista "Taxas de Referência - Usinas"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: STO.ANT.JARI; Mês Ref: 2014-09; TEIF Ref: 0,02533; IP Ref: 0,08091"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: U.SOBRADINHO; Mês Ref: 1979-4; TEIF Ref: 0,02533; IP Ref: 0,08091"
@CT3.1.1.2
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP existente (Usina) "cosr-ne1" e perfil "COSR-NE" 
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "0,08091" para o campo "IP" na guia "Usinas"
Então eu deveria ver 1 itens na lista "Taxas de Referência - Usinas"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: U.SOBRADINHO; Mês Ref: 1979-4; TEIF Ref: 0,02533; IP Ref: 0,08091"
@CT3.1.1.3
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP inexistente (Usina) com usuário "cnos" e perfil "CNOS"
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "9999" para o campo "IP" na guia "Usinas"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Usinas"
@CT3.1.1.4
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP inexistente (Usina) com usuário "cosr-ne1" e perfil "COSR-NE" 
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "9999" para o campo "IP" na guia "Usinas"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Usinas"
@CT3.1.1.5
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP existente (Interligação Internacional) com usuário "cnos" e perfil "CNOS"
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "0,0274" para o campo "IP" na guia "Interligações Internacionais"
Então eu deveria ver 1 itens na lista "Taxas de Referência - Interligações Internacionais"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 2; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0,0274"
@CT3.1.1.6
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP existente (Interligação Internacional)  com usuário "cosr-s1" e perfil "COSR-S"
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S"
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "0,0274" para o campo "IP" na guia "Interligações Internacionais"
Então eu deveria ver 1 itens na lista "Taxas de Referência - Interligações Internacionais"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 2; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0.0274"
@CT3.1.2.1
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP inexistente (Interligação Internacional) com usuário "cnos" e perfil "CNOS" 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "9999" para o campo "IP" na guia "Interligações Internacionais"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Interligações Internacionais"
@CT3.1.2.2
Cenário: Consultar Taxa de Referência filtrando pela IPEscolher uma IP inexistente (Interligação Internacional) com usuário "cosr-s1" e perfil "COSR-S" 
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligação Internacional"
E eu informo o valor "9999" para o campo "IP" na guia "Interligações Internacionais"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Interligações Internacionais"
#Funcionalidade: Consultar Taxa de Referência filtrando pela TEIF
@CT3.2.1.1
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF existente (Usina) com usuário "cnos" e perfil "CNOS" 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "0,02533" para o campo "TEIF" na guia "Usinas"
Então eu deveria ver 2 itens na lista "Taxas de Referência - Usinas"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: STO.ANT.JARI; Mês Ref: 2014-09; TEIF Ref: 0,02533; IP Ref: 0,08091"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: U.SOBRADINHO; Mês Ref: 1979-4; TEIF Ref: 0,02533; IP Ref: 0,08091"
@CT3.2.1.2
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF existente (Usina)  com usuário "cosr-ne1" e perfil "COSR-NE" 
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "0,02533" para o campo "TEIF" na guia "Usinas"
Então eu deveria ver 1 itens na lista "Taxas de Referência - Usinas"
E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores "Instalação: U.SOBRADINHO; Mês Ref: 1979-4; TEIF Ref: 0,02533; IP Ref: 0,08091"
@CT3.2.1.3
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF existente (Interligação Internacional) com usuário "cnos" e perfil "CNOS" 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "0" para o campo "TEIF" na guia "Interligações Internacionais"
Então eu deveria ver 2 itens na lista "Taxas de Referência - Interligações Internacionais"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 1; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0,03"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 2; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0,0274"
@CT3.2.1.4
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF existente (Interligação Internacional) com usuário "cosr-s1" e perfil "COSR-S"  
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "0" para o campo "TEIF" na guia "Interligações Internacionais"
Então eu deveria ver 2 itens na lista "Taxas de Referência - Interligações Internacionais"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 1; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0,03"
E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores "Instalação: CI CV.GARABI 2; Mês Ref: 2001-1; TEIF Ref: 0; IP Ref: 0,0274"
@CT3.2.2.1
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF inexistente (Usina) com usuário "cnos" e perfil "CNOS"
Dado que eu esteja na página "Autenticação"
Quando eu me autentico com usuário "cnos" e perfil "CNOS"
E eu aperto "Consultar taxas de referência"
E eu informo o valor "9999" para o campo "TEIF" na guia "Usina"
Então eu deveria ver 0 itens na lista "Taxas de Referência - "Usina"
@CT3.2.2.2
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF inexistente (Usina)  com usuário "cosr-ne1" e perfil "COSR-NE"
Dado que eu esteja na página "Autenticação"
Quando eu me autentico com usuário "cosr-ne1" e perfil "COSR-NE"
E eu aperto "Consultar taxas de referência"
E eu informo o valor "9999" para o campo "TEIF" na guia "Usina"
Então eu deveria ver 0 itens na lista "Taxas de Referência - "Usina"
@CT3.2.2.3
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF inexistente (Interligação Internacional) com usuário "cnos" e perfil "CNOS"
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS"
E eu esteja na página "Consultar taxas de referência"
Quando eu informo o valor "9999" para o campo "TEIF" na guia "Interligações Internacionais"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Interligações Internacionais"
@CT3.2.2.4
Cenário: Consultar Taxa de Referência filtrando pela TEIFEscolher uma TEIF inexistente (Interligação Internacional) com usuário "cosr-s1" e perfil "COSR-S"
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S"
E eu esteja na página "Consultar taxas de referência"
Quando eu informo o valor "9999" para o campo "TEIF" na guia "Interligações Internacionais"
Então eu deveria ver 0 itens na lista "Taxas de Referência - Interligações Internacionais"
#Funcionalidade: Exportar para Excel
@CT3.3.1.1
Cenário: Exportar para ExcelQuando não houver informações de taxas exibidas em tela
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "9999" para o campo "TEIF" na guia "Usinas"
E eu aperto o botão "Exportar Excel"
Então eu deveria ver a mensagem de erro de código "RS_MENS_015"
@CT3.3.1.2
Cenário: Exportar para ExcelQuando não houver informações de taxas exibidas em tela
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Interligações Internacionais"
E eu informo o valor "9999" para o campo "TEIF" na guia "Interligações Internacionais"
E eu aperto o botão "Exportar Excel"
Então eu deveria ver a mensagem de erro de código "RS_MENS_015"
@CT3.3.2.1
Cenário: Exportar para ExcelQuando houver informações de taxas exibidas em tela com usuário "cnos" e perfil "CNOS"
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS"
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu aperto o botão "Exportar Excel"
Então eu deveria poder baixar um arquivo Excel "Taxas de Referência"
@CT3.3.2.2
Cenário: Exportar para ExcelQuando houver informações de taxas exibidas em tela com usuário "cosr-ne1" e perfil "COSR-NE"
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE"
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu aperto o botão "Exportar Excel"
Então eu deveria poder baixar um arquivo Excel "Taxas de Referência"
@CT3.3.3.1
Cenário: Exportar para ExcelQuando houver informações de taxas filtradas em tela com usuário "cnos" e perfil "CNOS" 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "UT" para o campo "Instalação" na guia "Usinas"
E eu aperto o botão "Exportar Excel"
Então eu deveria poder baixar um arquivo Excel "Taxas de Referência"
@CT3.3.3.2
Cenário: Exportar para ExcelQuando houver informações de taxas filtradas em tela com usuário "cosr-se1" e perfil "COSR-SE" 
Dado que eu esteja autenticado com usuário "cosr-se1" e perfil "COSR-SE" 
E eu esteja na página "Consultar taxas de referência"
Quando eu aperto a guia "Usinas"
E eu informo o valor "UT" para o campo "Instalação" na guia "Usinas"
E eu aperto o botão "Exportar Excel"
Então eu deveria poder baixar um arquivo Excel "Taxas de Referência"
