# language: pt

#verificar CN02 - filtros
Funcionalidade: Consultar Taxa de Referência informando filtro por tipo de instalação

Cenário: Testar o comportamento do filtro tipo de  instalação Sem escolher instalação (Sucesso) com usuário "cnos" e perfil "CNOS" 
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Consultar taxas de referência"
	Então eu deveria ver 16 itens na lista "Taxas de Referência - Usinas"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "BENTO MUNHOZ"; Mês Ref: "1980-10"; TEIF Ref: "0,02917"; IP Ref: "0,12122"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CAMPOS"; Mês Ref: "1977-07"; TEIF Ref: "0,0206"; IP Ref: "0,1225"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CANDIOTA III"; Mês Ref: "2014-06"; TEIF Ref: "0,16438"; IP Ref: "0,10274"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CANDIOTA III"; Mês Ref: "2011-01"; TEIF Ref: "0,055"; IP Ref: "0,041"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "P.Medici"; Mês Ref: "1974-01"; TEIF Ref: "0,1338"; IP Ref: "0,0978"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM I"; Mês Ref: "2012-12"; TEIF Ref: "0,017"; IP Ref: "0,083"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM II"; Mês Ref: "2013-10"; TEIF Ref: "0,015"; IP Ref: "0,035"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "STO.ANT.JARI"; Mês Ref: "2014-09"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "TERMONORTE I"; Mês Ref: "1990-12"; TEIF Ref: "0,05"; IP Ref: "0,05"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.CHARQUEADAS"; Mês Ref: "1962-01"; TEIF Ref: "0,1394"; IP Ref: "0,1225"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.SOBRADINHO"; Mês Ref: "1979-04"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UHE BALBINA"; Mês Ref: "2015-05"; TEIF Ref: "0,01672"; IP Ref: "0,05403"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UHE JIRAU"; Mês Ref: "2013-09"; TEIF Ref: "0,005"; IP Ref: "0"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "USINA XINGO"; Mês Ref: "1994-04"; TEIF Ref: "0,06"; IP Ref: "0,08"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT MARIO LAGO"; Mês Ref: "2001-12"; TEIF Ref: "0,035"; IP Ref: "0,02"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT. FORTALEZA"; Mês Ref: "2003-12"; TEIF Ref: "0,0194"; IP Ref: "0,0191"
	
Cenário: Testar o comportamento do filtro tipo de  instalação Sem escolher instalação (Sucesso) "cosr-ne1" e perfil "COSR-NE"
	Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
	E eu esteja na página "Consultar taxas de referência"
	Então eu deveria ver 5 itens na lista "Taxas de Referência - Usinas"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM I"; Mês Ref: "2012-12"; TEIF Ref: "0,017"; IP Ref: "0,083"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM II"; Mês Ref: "2013-10"; TEIF Ref: "0,015"; IP Ref: "0,035"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.SOBRADINHO"; Mês Ref: "1979-04"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT. FORTALEZA"; Mês Ref: "2003-12"; TEIF Ref: "0,0194"; IP Ref: "0,0191"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "USINA XINGO"; Mês Ref: "1994-04"; TEIF Ref: "0,06"; IP Ref: "0,08"

Cenário: Testar o comportamento do filtro tipo de  instalação  Escolher Interligação Internacional (Sucesso) com usuário "cnos" e perfil "CNOS" 
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Consultar taxas de referência"
	Quando eu aperto a guia "Interligações Internacionais"
	Então eu deveria ver 2 itens na lista "Taxas de Referência - Interligações Internacionais"
	E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores Instalação: "CI CV.GARABI 1"; Mês Ref: "2001-01"; TEIF Ref: "0"; IP Ref: "0,03"
	E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores Instalação: "CI CV.GARABI 2"; Mês Ref: "2001-01"; TEIF Ref: "0"; IP Ref: "0,0274"
	
Cenário: Testar o comportamento do filtro tipo de  instalação  Escolher Interligação Internacional (Insucesso) com usuário "cosr-ne1" e perfil "COSR-NE" 
	Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
	E eu esteja na página "Consultar taxas de referência"
	Então eu não deveria ver a aba Taxas de Referência - "Interligações Internacionais"
	
Cenário: Testar o comportamento do filtro tipo de  instalação  Escolher Interligação Internacional (Sucesso) com usuário "cosr-s1" e perfil "COSR-S" 
	Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
	E eu esteja na página "Consultar taxas de referência"
	Quando eu aperto a guia "Interligações Internacionais"
	Então eu deveria ver 2 itens na lista "Taxas de Referência - Interligações Internacionais"
	E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores Instalação: "CI CV.GARABI 1"; Mês Ref: "2001-01"; TEIF Ref: "0"; IP Ref: "0,03"
	E eu deveria ver um item na lista "Taxas de Referência - Interligações Internacionais" com os valores Instalação: "CI CV.GARABI 2"; Mês Ref: "2001-01"; TEIF Ref: "0"; IP Ref: "0,0274"

Cenário: Testar o comportamento do filtro tipo de  instalação Escolher Usina (Sucesso) com usuário "cnos" e perfil "CNOS" 
	Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
	E eu esteja na página "Consultar taxas de referência"
	Quando eu aperto a guia "Usinas"
	Então eu deveria ver 16 itens na lista "Taxas de Referência - Usinas"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "BENTO MUNHOZ"; Mês Ref: "1980-10"; TEIF Ref: "0,02917"; IP Ref: "0,12122"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CAMPOS"; Mês Ref: "1977-07"; TEIF Ref: "0,0206"; IP Ref: "0,1225"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CANDIOTA III"; Mês Ref: "2014-06"; TEIF Ref: "0,16438"; IP Ref: "0,10274"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "CANDIOTA III"; Mês Ref: "2011-01"; TEIF Ref: "0,055"; IP Ref: "0,041"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "P.Medici"; Mês Ref: "1974-01"; TEIF Ref: "0,1338"; IP Ref: "0,0978"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM I"; Mês Ref: "2012-12"; TEIF Ref: "0,017"; IP Ref: "0,083"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM II"; Mês Ref: "2013-10"; TEIF Ref: "0,015"; IP Ref: "0,035"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "STO.ANT.JARI"; Mês Ref: "2014-09"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "TERMONORTE I"; Mês Ref: "1990-12"; TEIF Ref: "0,05"; IP Ref: "0,05"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.CHARQUEADAS"; Mês Ref: "1962-01"; TEIF Ref: "0,1394"; IP Ref: "0,1225"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.SOBRADINHO"; Mês Ref: "1979-04"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UHE BALBINA"; Mês Ref: "2015-05"; TEIF Ref: "0,01672"; IP Ref: "0,05403"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UHE JIRAU"; Mês Ref: "2013-09"; TEIF Ref: "0,005"; IP Ref: "0"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "USINA XINGO"; Mês Ref: "1994-04"; TEIF Ref: "0,06"; IP Ref: "0,08"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT MARIO LAGO"; Mês Ref: "2001-12"; TEIF Ref: "0,035"; IP Ref: "0,02"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT. FORTALEZA"; Mês Ref: "2003-12"; TEIF Ref: "0,0194"; IP Ref: "0,0191"
	
Cenário: Testar o comportamento do filtro tipo de  instalação Escolher Usina (Sucesso) com usuário "cosr-ne1" e perfil "COSR-NE" 
	Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
	E eu esteja na página "Consultar taxas de referência"
	Quando eu aperto a guia "Usinas"
	Então eu deveria ver 5 itens na lista "Taxas de Referência - Usinas"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM I"; Mês Ref: "2012-12"; TEIF Ref: "0,017"; IP Ref: "0,083"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "PORTO PECEM II"; Mês Ref: "2013-10"; TEIF Ref: "0,015"; IP Ref: "0,035"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "U.SOBRADINHO"; Mês Ref: "1979-04"; TEIF Ref: "0,02533"; IP Ref: "0,08091"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "UT. FORTALEZA"; Mês Ref: "2003-12"; TEIF Ref: "0,0194"; IP Ref: "0,0191"
	E eu deveria ver um item na lista "Taxas de Referência - Usinas" com os valores Instalação: "USINA XINGO"; Mês Ref: "1994-04"; TEIF Ref: "0,06"; IP Ref: "0,08"

