# language: pt
Funcionalidade: Verificar Filtros de Eventos
@CT3.1.1
Cenário: 1) Usar um nome de usina existente 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "15/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "SOBRA" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 6 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG2; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG3; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG4; Data Hora: 01/01/2001 00:00; Estado Operativo: LCS; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG5; Data Hora: 01/01/2001 00:00; Estado Operativo: LCS; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG6; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com o valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG5; Data Hora: 12/01/2001 08:09; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
@CT3.1.2
Cenário: 2) Usar um nome de usina inexistente
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/05/2001" para o campo "Data Inicial"
E eu informo o valor "15/05/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.1.3
Cenário: 3) Usar um nome de Interligação internacional existente 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/03/2002" para o campo "Data Inicial"
E eu informo o valor "19/03/2002" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "GARABI" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 6 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 18/03/2002 02:16; Estado Operativo: LIG; Condição Operativa: RPR; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 18/03/2002 23:46; Estado Operativo: DAU; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 19/03/2002 05:55; Estado Operativo:LIG; Condição Operativa: RPR; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 19/03/2002 06:12; Estado Operativo:DAU;  Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 1; Data Hora: 14/03/2002 20:05; Estado Operativo: LIG; Condição Operativa: RFO; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 1; Data Hora: 14/03/2002 20:57; Estado Operativo: DCO; Condição Operativa: NOR; Disponibilidade: 1030,000"
@CT3.1.4
Cenário: 4) Usar um nome de Interligação internacional  inexistente
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/01/2001" para o campo "Data Inicial"
E eu informo o valor "13/01/2001" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.2.1
Cenário: 1) Usar um código de unidade geradora existente 
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/10/2001" para o campo "Data Inicial"
E eu informo o valor "15/10/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas"
E eu aperto o botão "Pesquisar"
E eu informo o valor "RJU" para o campo "Unidade Geradora" no grid "Eventos"
Então eu deveria ver 1 item no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CAMPOS; Unidade Geradora: RJUSCP_13P8_UG2; Data Hora: 10/10/2001 14:58; Estado Operativo: LIG; Condição Operativa: RFO; Disponibilidade: 10,000"
#
@CT3.2.2
Cenário: 2) Usar um código de unidade geradora de uma instalação que não foi selecionada na pesquisa
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2002" para o campo "Data Inicial"
E eu informo o valor "04/01/2002" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
E eu informo o valor "RJUSCP_13P8_UG1" para o campo "Unidade Geradora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.2.3
Cenário: 3) Usar um código de interligação internacional existente
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2004" para o campo "Data Inicial"
E eu informo o valor "05/01/2004" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "CI ACARAY" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 5 item no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 01:18; Estado Operativo: DAU; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 01:35; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 05/01/2004 12:22; Estado Operativo: DUR; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 05/01/2004 14:54; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
@CT3.2.4
Cenário: 4) Usar um código de interligação internacional  de uma instalação que não foi selecionada na pesquisa
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2004" para o campo "Data Inicial"
E eu informo o valor "05/01/2004" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono o item "CI CV.GARABI 1" na lista "Interligações Internacionais"
E eu seleciono o item "CI CV.GARABI 2" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "ACARAY" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.3.1
Cenário: 1) Escolher uma Data/Hora existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "10/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "03/Janeiro/2001 10:01" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 1 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: BENTO MUNHOZ; Unidade Geradora: PRGBM_16P5_UG4; Data Hora: 03/01/2001 10:01; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 419,000"
@CT3.3.2
Cenário: 2) Escolher uma Data/Hora não existente no período selecionado (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "15/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "11/01/2001 00:00" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
#Eventos - Usinas
@CT3.3.3
Cenário: 3) Escolher uma Data/Hora inválida (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "31/12/2003" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "31/01/2001 00:00" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.4.1
Cenário: 1) Escolher um Estado Operativo existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 43 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Estado Operativo: LIG"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.4.2
Cenário: 2) Escolher um Estado Operativo não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "DPR" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.4.3
Cenário: 3) Escolher um Estado Operativo inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "10/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.5.1
Cenário: 1) Escolher uma Condição Operativa existente (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "NOR" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 53 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Condição Operativa: NOR"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.5.2
Cenário: 2) Escolher uma Condição Operativa não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "NOT" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.5.3
Cenário: 3) Escolher um Condição Operativa inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.6.1
Cenário: 1) Escolher uma Origem existente
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "GUM" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 12 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Origem: GUM"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.6.2
Cenário: 2) Escolher uma Origem não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "GCB" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.6.3
Cenário: 3) Escolher um Origem inválida (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.7.1
Cenário: 1) Escolher combinações entre Estado Operativo,  Condição Operativa e Origem (Sucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
E eu informo o valor "RFO" para o campo "Condição Operativa" no grid "Eventos"
E eu informo o valor "GUM" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 5 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Estado Operativo: LIG; Condição Operativa: RFO; Origem: GUM"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.7.2
Cenário: 2) Escolher combinações entre Estado Operativo,  Condição Operativa e Origem (Insucesso)
Dado que eu esteja autenticado com usuário "cnos" e perfil "CNOS" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
E eu informo o valor "RFO" para o campo "Condição Operativa" no grid "Eventos"
E eu informo o valor "GCB" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
#Funcionalidade: Verificar Filtros de Eventos
@CT3.8.1
Cenário: 1) Usar um nome de usina existente 
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "15/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "SOBRA" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 6 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG2; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG3; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG4; Data Hora: 01/01/2001 00:00; Estado Operativo: LCS; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG5; Data Hora: 01/01/2001 00:00; Estado Operativo: LCS; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG6; Data Hora: 01/01/2001 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: U.SOBRADINHO; Unidade Geradora: BAUSB_13P8_UG5; Data Hora: 12/01/2001 08:09; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 175,000"
@CT3.8.2
Cenário: 2) Usar um nome de usina inexistente
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/05/2001" para o campo "Data Inicial"
E eu informo o valor "15/05/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.8.3
Cenário: 3) Usar um nome de Interligação internacional existente 
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/03/2002" para o campo "Data Inicial"
E eu informo o valor "19/03/2002" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "GARABI" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 6 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 18/03/2002 02:16; Estado Operativo: LIG; Condição Operativa: RPR; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 18/03/2002 23:46; Estado Operativo: DAU; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 19/03/2002 05:55; Estado Operativo:LIG; Condição Operativa: RPR; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 2; Data Hora: 19/03/2002 06:12; Estado Operativo:DAU;  Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 1; Data Hora: 14/03/2002 20:05; Estado Operativo: LIG; Condição Operativa: RFO; Origem: EXT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI CV.GARABI 1; Data Hora: 14/03/2002 20:57; Estado Operativo: DCO; Condição Operativa: NOR; Disponibilidade: 1030,000"
@CT3.8.4
Cenário: 4) Usar um nome de Interligação internacional  inexistente
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/01/2001" para o campo "Data Inicial"
E eu informo o valor "13/01/2001" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.9.1
Cenário: 1) Usar um código de unidade geradora existente 
Dado que eu esteja autenticado com usuário "cosr-se1" e perfil "COSR-SE"
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "10/10/2001" para o campo "Data Inicial"
E eu informo o valor "15/10/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas"
E eu aperto o botão "Pesquisar"
E eu informo o valor "RJU" para o campo "Unidade Geradora" no grid "Eventos"
Então eu deveria ver 1 item no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CAMPOS; Unidade Geradora: RJUSCP_13P8_UG2; Data Hora: 10/10/2001 14:58; Estado Operativo: LIG; Condição Operativa: RFO; Disponibilidade: 10,000"
#
@CT3.9.2
Cenário: 2) Usar um código de unidade geradora de uma instalação que não foi selecionada na pesquisa
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2002" para o campo "Data Inicial"
E eu informo o valor "04/01/2002" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono o item "U.SOBRADINHO" na lista "Usinas"
E eu aperto o botão "Pesquisar"
E eu informo o valor "RJUSCP_13P8_UG1" para o campo "Unidade Geradora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.9.3
Cenário: 3) Usar um código de interligação internacional existente
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2004" para o campo "Data Inicial"
E eu informo o valor "05/01/2004" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono todos os itens na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "CI ACARAY" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 5 item no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 00:00; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 01:18; Estado Operativo: DAU; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 01/01/2004 01:35; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 05/01/2004 12:22; Estado Operativo: DAU; Origem: INT; Disponibilidade: 0,000"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: CI ACARAY; Data Hora: 05/01/2004 14:54; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 50,000"
@CT3.9.4
Cenário: 4) Usar um código de interligação internacional  de uma instalação que não foi selecionada na pesquisa
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2004" para o campo "Data Inicial"
E eu informo o valor "05/01/2004" para o campo "Data Final"
E eu aperto a guia "Interligações Internacionais"
E eu seleciono o item "CI CV.GARABI 1" na lista "Interligações Internacionais"
E eu seleciono o item "CI CV.GARABI 2" na lista "Interligações Internacionais"
E eu aperto o botão "Pesquisar"
E eu informo o valor "ACARAY" para o campo "Instalação" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.10.1
Cenário: 1) Escolher uma Data/Hora existente (Sucesso)
Dado que eu esteja autenticado com usuário "cosr-s1" e perfil "COSR-S" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "10/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "03/Janeiro/2001 10:01" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 1 itens no grid "Eventos"
E eu deveria ver um item no grid "Eventos" com valor "Instalação: BENTO MUNHOZ; Unidade Geradora: PRGBM_16P5_UG4; Data Hora: 03/01/2001 10:01; Estado Operativo: LIG; Condição Operativa: NOR; Disponibilidade: 419,000"
@CT3.10.2
Cenário: 2) Escolher uma Data/Hora não existente no período selecionado (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "15/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "11/01/2001 00:00" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.10.3
Cenário: 3) Escolher uma Data/Hora inválida (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "31/12/2003" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "31/01/2001 00:00" para o campo "Data/Hora" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.11.1
Cenário: 1) Escolher um Estado Operativo existente (Sucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 11 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Estado Operativo: LIG"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.11.2
Cenário: 2) Escolher um Estado Operativo não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "DPR" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.11.3
Cenário: 3) Escolher um Estado Operativo inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "10/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Estado Operativo" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.12.1
Cenário: 1) Escolher uma Condição Operativa existente (Sucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "NOR" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 16 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Condição Operativa: NOR"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "03/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.12.2
Cenário: 2) Escolher uma Condição Operativa não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "NOT" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.12.3
Cenário: 3) Escolher um Condição Operativa inválido (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE"
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Condição Operativa" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.13.1
Cenário: 1) Escolher uma Origem existente
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "31/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "GUM" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 1 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Origem: GUM"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/01/2001" e "31/01/2001"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.13.2
Cenário: 2) Escolher uma Origem não existente na lista de eventos (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "GCB" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.13.3
Cenário: 3) Escolher um Origem inválida (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE" 
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/01/2001" para o campo "Data Inicial"
E eu informo o valor "03/01/2001" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "ZZZ" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
@CT3.14.1
Cenário: 1) Escolher combinações entre Estado Operativo,  Condição Operativa e Origem (Sucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE"
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/03/2008" para o campo "Data Inicial"
E eu informo o valor "31/03/2008" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
E eu informo o valor "RFO" para o campo "Condição Operativa" no grid "Eventos"
E eu informo o valor "GUM" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 2 itens no grid "Eventos"
E todo item do grid "Eventos" deveria ter o valor "Estado Operativo: LIG; Condição Operativa: RFO; Origem: GUM"
E todo item do grid "Eventos" deveria ter "Data Hora" entre "01/03/2008" e "31/03/2008"
#(realizar o filtro na guia "Eventos - Usinas")
@CT3.14.2
Cenário: 2) Escolher combinações entre Estado Operativo,  Condição Operativa e Origem (Insucesso)
Dado que eu esteja autenticado com usuário "cosr-ne1" e perfil "COSR-NE"
E eu esteja na página "Consultar eventos"
Quando eu informo o valor "01/03/2008" para o campo "Data Inicial"
E eu informo o valor "31/03/2008" para o campo "Data Final"
E eu aperto a guia "Usinas"
E eu seleciono todos os itens na lista "Usinas" 
E eu aperto o botão "Pesquisar"
E eu informo o valor "LIG" para o campo "Estado Operativo" no grid "Eventos"
E eu informo o valor "RFO" para o campo "Condição Operativa" no grid "Eventos"
E eu informo o valor "GCB" para o campo "Origem" no grid "Eventos"
Então eu deveria ver 0 itens no grid "Eventos"
